# Generated by Django 4.2.17 on 2025-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Ben's Blog", max_length=200, unique=True),
        ),
    ]
