# Generated by Django 4.2.17 on 2025-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_title_tag_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='blog home', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
