# Generated by Django 4.2.17 on 2025-01-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
